# Generated by Django 5.0.4 on 2024-05-11 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='max_helpers',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
