# Generated by Django 5.0.4 on 2024-05-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0002_subsidiary_max_helpers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
