# Generated by Django 5.0.4 on 2024-05-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useraccount_id_subsidiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
