# Generated by Django 5.0.4 on 2024-05-10 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0001_initial'),
        ('user', '0002_useraccount_id_subsidiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_helper', models.BooleanField(default=False)),
                ('is_exchanger', models.BooleanField(default=False)),
                ('id_subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiary.subsidiary')),
            ],
            options={
                'verbose_name': 'usuario general',
                'verbose_name_plural': 'usuarios generales',
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_register', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
