# Generated by Django 5.0.4 on 2024-05-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_is_active_usergeneral_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGeneral',
        ),
    ]
