# Generated by Django 5.0.4 on 2024-05-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='rejected_posts',
            field=models.IntegerField(default=0),
        ),
    ]
