# Generated by Django 5.0.4 on 2024-05-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_usergeneral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_exchanger',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_helper',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HELPER', 'Helper'), ('EXCHANGER', 'Exchanger')], default='EXCHANGER', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6),
        ),
    ]
