# Generated by Django 5.0.4 on 2024-05-30 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0009_post_stock_product'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='post_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_send', to='app_post.post'),
        ),
        migrations.AlterField(
            model_name='request',
            name='post_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_receive', to='app_post.post'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='request.requeststate'),
        ),
    ]
