# Generated by Django 5.0.4 on 2024-05-31 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0009_post_stock_product'),
        ('request', '0002_alter_request_post_maker_alter_request_post_receive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user_maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_send', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_receive',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_receive', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='post_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts_send', to='app_post.post'),
        ),
        migrations.AlterField(
            model_name='request',
            name='post_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts_receive', to='app_post.post'),
        ),
    ]
