# Generated by Django 5.0.4 on 2024-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request_user_maker_request_user_receive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejected',
            field=models.IntegerField(default=0),
        ),
    ]
