# Generated by Django 5.0.4 on 2024-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_request_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='day_of_request',
            field=models.DateField(blank=True, null=True),
        ),
    ]
