# Generated by Django 5.0.4 on 2024-06-22 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_post', '0009_post_stock_product'),
        ('subsidiary', '0004_alter_subsidiary_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_in_filial', to='app_post.category')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock', to='subsidiary.subsidiary')),
            ],
        ),
    ]
