# Generated by Django 5.0.4 on 2024-05-30 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_post', '0009_post_stock_product'),
        ('subsidiary', '0004_alter_subsidiary_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_maker', models.CharField(max_length=255)),
                ('code_received', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turns_made', to='app_post.post')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subsidiary.subsidiary')),
                ('user_maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turns_made', to=settings.AUTH_USER_MODEL)),
                ('user_received', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turns_received', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turn.turnstate')),
            ],
        ),
    ]
