# Generated by Django 5.0.4 on 2024-06-02 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_request_day_of_request'),
        ('turn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turns', to='request.request'),
        ),
    ]
