# Generated by Django 5.0.4 on 2024-06-03 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0009_post_stock_product'),
        ('turn', '0002_alter_turn_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='request',
        ),
        migrations.AddField(
            model_name='turn',
            name='day_of_turn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='post_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turns_send', to='app_post.post'),
        ),
        migrations.AddField(
            model_name='turn',
            name='post_receive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turns_receive', to='app_post.post'),
        ),
    ]
