# Generated by Django 5.0.4 on 2024-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
