# Generated by Django 5.0.4 on 2024-05-09 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_post.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_post.poststate'),
        ),
    ]
