# Generated by Django 5.0.4 on 2024-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0004_post_image_1_post_image_2_post_image_3_post_image_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(upload_to='post_images/'),
        ),
    ]
