# Generated by Django 5.0.4 on 2024-05-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0005_alter_post_image_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='stateProduct',
            new_name='state_product',
        ),
    ]
