# Generated by Django 5.0.4 on 2024-05-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0007_remove_post_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='app_post.poststate'),
        ),
    ]
