# Generated by Django 5.0.4 on 2024-05-15 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0008_alter_post_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stock_product',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
